### PR TITLE
Update duckstation-qt_pt-br.ts

### PR DESCRIPTION
**Pull request by altiereslima**

### CODE REVIEW

**Comment by andercard0** [comment]
@stenzek Those changes are already mergerd in #2324, only thing I left out was "nearest-neighbor" term because it does not make any sense to translate it literally, but thanks anyway!

**Comment by altiereslima** [comment]
> @stenzek Those changes are already mergerd in #2324, only thing I left out was "nearest-neighbor" term because it does not make any sense to translate it literally, but thanks anyway!

O Paint.net traduz esse termo como "Vizinho mais próximo" e o Photoshop traduz esse termo como "Pelo mais próximo"

**Comment by andercard0** [comment]
> 
> 
> > @stenzek Those changes are already mergerd in #2324, only thing I left out was "nearest-neighbor" term because it does not make any sense to translate it literally, but thanks anyway!
> 
> O Paint.net traduz esse termo como "Vizinho mais próximo" e o Photoshop traduz esse termo como "Pelo mais próximo"

All good, I've updated it as you mentioned here #2324 no problem! Just next time keep your explanations in English.

**Comment by stenzek** [comment]
Superseded by #2324

**Pull request closed without merging**
