### PR TITLE
Use proper 21:9 aspect ratio, add 32:9

### PR DESCRIPTION
**Pull request by Margen67**
https://en.wikipedia.org/wiki/Ultrawide_formats#Ultrawide_Cinema

### CODE REVIEW

**Comment by stenzek** [comment]
Thanks! The GTE should probably be updated to include these new ratios, so it works with the widescreen hack.

https://github.com/stenzek/duckstation/blob/master/src/core/gte.cpp#L620 and https://github.com/stenzek/duckstation/blob/master/src/core/gte.cpp#L715

I believe this should be `(x * 9) / 16` for 21:9 (64:27), and `(x * 3) / 8` for 32:9.

**Comment by Margen67** [comment]
> 
> 
> Thanks! The GTE should probably be updated to include these new ratios, so it works with the widescreen hack.
> 
> https://github.com/stenzek/duckstation/blob/master/src/core/gte.cpp#L620 and https://github.com/stenzek/duckstation/blob/master/src/core/gte.cpp#L715
> 
> I believe this should be `(x * 9) / 16` for 21:9 (64:27), and `(x * 3) / 8` for 32:9.

@stenzek What should the Sx values be?

**Comment by Margen67** [comment]
> 
> 
> Thanks! The GTE should probably be updated to include these new ratios, so it works with the widescreen hack.
> 
> https://github.com/stenzek/duckstation/blob/master/src/core/gte.cpp#L620 and https://github.com/stenzek/duckstation/blob/master/src/core/gte.cpp#L715
> 
> I believe this should be `(x * 9) / 16` for 21:9 (64:27), and `(x * 3) / 8` for 32:9.

Done.

**Comment by stenzek** [comment]
Thanks! The game list cache version will need to be changed because the array indices for some of the ratios will be different now, but I'll take care of that :)

**Pull request merged**
