### PR TITLE
Add Y values for aspect scaling

### PR DESCRIPTION
**Pull request by Muzzarino**

### CODE REVIEW

**Comment by stenzek** [comment]
Not really sure what you're trying to accomplish here?

**Comment by Muzzarino** [comment]
> Not really sure what you're trying to accomplish here?

The vertical fov should be scaled if below the native aspect ratio rather than cropping off the horizontal from 4:3.

**Comment by stenzek** [comment]
Unless I'm reading this wrong, you're effectively setting the screen-space coordinates to 1 for PGXP (which will break things), and using X (IR1) for both X and Y for native coordinates, and the `* 1 / 1` is redundant - so I don't see how this will produce correct results.

**Comment by Muzzarino** [comment]
> Unless I'm reading this wrong, you're effectively setting the screen-space coordinates to 1 for PGXP (which will break things), and using X (IR1) for both X and Y for native coordinates, and the `* 1 / 1` is redundant - so I don't see how this will produce correct results.



> Unless I'm reading this wrong, you're effectively setting the screen-space coordinates to 1 for PGXP (which will break things), and using X (IR1) for both X and Y for native coordinates, and the `* 1 / 1` is redundant - so I don't see how this will produce correct results.

It's to maintain the fov at it's original scale while the other is being extended.

**Comment by stenzek** [comment]
Have you actually tested this patch? I can't see how it would work at all with the current diff.

**Comment by stenzek** [comment]
Closing since the changes here break rendering. Happy to reconsider/merge if you fix it.

**Pull request closed without merging**
