### PR TITLE
update simple-chinese language file to latest.

### PR DESCRIPTION
**Pull request by zkdpower**
update simple-chinese language file to latest.

### CODE REVIEW

**Comment by zkdpower** [comment]
dear author, i found the translation text for OSD "No save state found in slot {}." are fail to show.
i have tested all language like Japanese, Portuguese.……

**Comment by Guwange** [comment]
> dear author, i found the translation text for OSD "No save state found in slot {}." are fail to show. i have tested all language like Japanese, Portuguese.……

@zkdpower , as commented on my post below, 
https://github.com/stenzek/duckstation/pull/2867#issuecomment-1219059324
now you need to execute scripts/generate_update_glyph_ranges.py with duckstation-qt_zh-cn.ts to update font list used to showing OSD.

**Comment by zkdpower** [comment]
> > dear author, i found the translation text for OSD "No save state found in slot {}." are fail to show. i have tested all language like Japanese, Portuguese.……
> 
> @zkdpower , as commented on my post below, [#2867 (comment)](https://github.com/stenzek/duckstation/pull/2867#issuecomment-1219059324) now you need to execute scripts/generate_update_glyph_ranges.py with duckstation-qt_zh-cn.ts to update font list used to showing OSD.

can you guide me how to execute scripts/generate_update_glyph_ranges.py for duckstation-qt_zh-cn.ts to generate suitable font ,please detail

**Comment by zkdpower** [comment]
> > dear author, i found the translation text for OSD "No save state found in slot {}." are fail to show. i have tested all language like Japanese, Portuguese.……
> 
> @zkdpower , as commented on my post below, [#2867 (comment)](https://github.com/stenzek/duckstation/pull/2867#issuecomment-1219059324) now you need to execute scripts/generate_update_glyph_ranges.py with duckstation-qt_zh-cn.ts to update font list used to showing OSD.

Guwange, Perhaps you misunderstood my means meaning, the issue about lack of words or show "???" both are solved by you since lastmonth.  the issue of OSD message "No save state found in slot {}."  now i found are always showing english. you can try to load a empty save with shortcut.

**Pull request merged**
