### PR TITLE
Update duckstation-qt_zh-cn.ts

### PR DESCRIPTION
**Pull request by phoe-nix**

### CODE REVIEW

**Comment by stenzek** [comment]
There are some orphaned strings here which aren't linked to any source files, and won't be used.

Please use the `lupdate` tool to sync the strings in the .ts file with the latest build. You can do this by cloning the repo (with submodules), and running `src\duckstation-qt\update_translations.bat`. This will add the new strings to the .ts file which you can translate.

**Comment by stenzek** [comment]
Superseded by #840 .

**Comment by phoe-nix** [comment]
I don't have that tool, I use notepad++, edit from pt-br.ts, i will try that tool
and gpu setting name changed to display in latest version, so I edit by myself. I tested on duckstation, no errors.
OSD font cant show Chinese, so i don't translate them.

**Comment by phoe-nix** [comment]
Sorry, I mean OSD font cant show Chinese in duckstation-sdl-x64-ReleaseLTCG.exe, but im not sure on latest version.
Our country blocked some websites, cant open wiki site.

**Comment by phoe-nix** [comment]
I thought qt used same font lol

**Comment by stenzek** [comment]
Oh, yes that's expected. Translations will only work in Qt.

Here is the content from the wiki page:

This page describes the process for creating and keeping a new translation up to date.

To create a new translation:
1. Clone the repository in the same way as described in the main README (submodules/recursive clone if on Windows).
2. Edit the file named `update_translations.bat` in `src\duckstation-qt` by copying/pasting one of the existing lines, and changing the language code at the end. You can find a list of language codes here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes (use the 639-1 code). If your language has different variants for multiple countries, append a two-letter country code at the end after an underscore. You can find a list of country codes here: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes (use the 3166-1 Alpha-2 code). The file name should follow the `appname_language[_country].ts` convention specified [here](https://doc.qt.io/qt-5/linguist-translators.html#changing-the-target-locale).
3. Run this batch file by double-clicking it. If you're on Linux, this won't work, so you should run `cd src/duckstation-qt` and `lupdate ./ -ts translations/duckstation-qt_LANGUAGE_CODE_HERE.ts` manually instead.
4. This should create a new `.ts` file for your language in the `translations` directory.
5. Open this new translation file in Qt Linguist. If you're on Linux, your package manager will provide it. If you're on Windows, a copy can be found in `dep\msvc\qt\5.15.0\msvc2017_64\bin\linguist.exe`.
6. If prompted, select your language and country. Leave the source language as POSIX.

To update an existing translation:
1. Update your Git repository by running `git pull`. If it gives you an error about local changes, run `git reset --hard` and `git clean -d -f -x` to clear them out, and run `git pull` again. But make sure you have nothing you want to save in the repo first, I won't take responsibility if you delete your work this way.
2. Run the `update_translations.bat` file first used to create the translation.
3. This will add the new strings to the `.ts` file and report how many new strings there are for translation, which you can open in Linguist and quickly jump to.

Translating strings:
1. For each form/context on the left, a list of strings will appear in the middle for translation. A mock version of the UI will also be displayed.
2. Go through each string, entering a translation in your target language in the text box below. Mark the string as completed (check mark) after doing so, this way when new strings are added you can jump directly to them.
3. To submit your translation or updates, follow the normal Git process for forking/creating a branch/creating a pull request. You only want to submit the changes to your language's `.ts` file, no other files. If you are unsure about how to do this, send your translation (`.ts` file) directly to Stenzek on Discord, and I'll commit/push it for you.

Also see the Qt reference manual here: https://doc.qt.io/qt-5/linguist-translators.html

We also have a `#translations` channel on Discord where questions can be asked/you can get clarification on technical terms.

**Comment by phoe-nix** [comment]
I dont have msvc2017_64. and i dont want to install.
I use lrelease.exe to convert.
Editing by notepad is no different, right? I checked all strings, everything did, but only few strings cant translate.
[setting]
"Restore Defaults", "Close"
[hotkey setting]
"General","Graphics","Save States","Audio"

**Comment by phoe-nix** [comment]
I found a Chinese character "拟" show "?" in OSD font. 
not sure if there are more characters show "?"

**Comment by stenzek** [comment]
Using Linguist gives you a nice interface to edit the strings, makes it a bit easier.

You need to use lupdate.exe as well - that will "add" any new strings from the emulator to the ts file so you can translate them. If you don't want to run this yourself I can provide an updated .ts file.

> I found a Chinese character "拟" show "?" in OSD font.

It's only using a subset of the characters, to keep the texture size small:
```cpp
const ImWchar*  ImFontAtlas::GetGlyphRangesChineseSimplifiedCommon()
{
    // Store 2500 regularly used characters for Simplified Chinese.
    // Sourced from https://zh.wiktionary.org/wiki/%E9%99%84%E5%BD%95:%E7%8E%B0%E4%BB%A3%E6%B1%89%E8%AF%AD%E5%B8%B8%E7%94%A8%E5%AD%97%E8%A1%A8
    // This table covers 97.97% of all characters used during the month in July, 1987.
```

This gives us a 2048x2048 texture at 150% scaling. I can use the "full" range if needed, although this results in a 4096x8192 texture, which is still fine for modern GPUs. You just can't reliably go beyond 16384 :)

**Comment by phoe-nix** [comment]
thanks, update .ts file when new version release.
about OSD font, its not important, i can use other characters instead.

**Pull request closed without merging**
