### PR TITLE
Spanish (Spain) translation update

### PR DESCRIPTION
**Pull request by IlDucci**
- Adding translations for the new strings (Big Picture, wireframe options, Setup Wizard...). WARNING!!! Big Picture mode was not tested in DuckStation because the strings are still being displayed in English, so I am unable to test them for the time being.
 - Some strings were copied from PCSX2 Spanish (Spain) translation, also worked on by myself.
 - Unification pass for certain terms.
 - Cleanup of unused strings. WARNING! A number of strings in the Settings menu have reverted back to English.

### CODE REVIEW

**Comment by stenzek** [comment]
> WARNING!!! Big Picture mode was not tested in DuckStation because the strings are still being displayed in English, so I am unable to test them for the time being.

Weird, it should be fine, I was only checking Korean before. Maybe the cache isn't being tossed...

**Comment by stenzek** [comment]
Can't reproduce that :/

**Comment by stenzek** [comment]
That assert should definitely never fire if you never started a game and/or big picture mode.

**Comment by IlDucci** [comment]
> That assert should definitely never fire if you never started a game and/or big picture mode.

Confirmed. Did a new cleaned folder without going there and the language selection shows no issues.

**Comment by stenzek** [comment]
Could you upload the `settings.ini` from the profile which had the issue? I'll try to reproduce with that when I have time.

Feel free to remove the paths and any RetroAchievements details, but otherwise there shouldn't be any other identifying information in there.

**Comment by IlDucci** [comment]
So the assertion failed disapppeared when I deleted the following files from my Users/USER/Documents/Duckstation folder:
- The DX caches.
- All the savestates (turns out there was quite a lot, so a lot of old ones were probably involved).
- All the screenshots.

Big Picture remains in English.

**Comment by IlDucci** [comment]
Settings file: [settings - copia.zip](https://github.com/stenzek/duckstation/files/12550064/settings.-.copia.zip)

**Pull request merged**
