### PR TITLE
Update the Simple-Chinese translation to latest.

### PR DESCRIPTION
**Pull request by zkdpower**
P.s.

**1. The icon of "Cover Downloader" is missing.
2.  When "CPU Debugger" already running then clicking on  MENU of it again will cause the program to crash.
3. The page of "General Setting" should be more long and more wide. It's best to remember the size and position by user's preference. besides, it's subpage of "advanced"-"tweak/hack" blank a little too much on the right. 
4. Switch between different themes will cause the width change of "Game list".**

### CODE REVIEW

**Comment by zkdpower** [comment]
> P.s.
> 
> **1. The icon of "Cover Downloader" is missing. 2. While "CPU Debugger" already running then clicking on MENU of it again will cause the program to crash. 3. The page of "General Setting" should be more long and more wide. It's best to remember the settings parameters by user-defined. and it's subpage of "advanced"-"tweak/hack" blank a little too much on the right. 4. Switch between different themes will cause the width change of "Game list".**

**Comment by zkdpower** [comment]
Hello, Author, Did you notice my message ?the 6401 still has previous version problem.

**Comment by stenzek** [comment]
1. I don't really care about icons for cover downloader.
2. Debugger currently has a bunch of issues, I am fixing those separately.
3. I can't make the settings dialogs larger, because users with 768p displays complain.
4. Qt issue, don't really care for fixing it, because changing themes is so infrequent.

**Comment by zkdpower** [comment]
please fix icons when you free.&nbsp;&nbsp;


游戏音乐种花
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Connor ***@***.***&gt;; 
发送时间: 2024年2月24日(星期六) 下午3:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [stenzek/duckstation] Update the Simple-Chinese translation to latest. (PR #3122)





  
I don't really care about icons for cover downloader.
 
Debugger currently has a bunch of issues, I am fixing those separately.
 
I can't make the settings dialogs larger, because users with 768p displays complain.
 
Qt issue, don't really care for fixing it, because changing themes is so infrequent.
  
&mdash;

**Pull request merged**
