### PR TITLE
update Simple-Chinese Translation.

### PR DESCRIPTION
**Pull request by zkdpower**
update Simple-Chinese Translation.

besides, please add following string for my translation:

Automatic

Stretch To Fill

Nearest-Neighbor
Bilinear (Smooth)
Nearest-Neighbor (Integer)
Bilinear (Sharp)

Disabled
Overlay Wireframe
Only Wireframe

Cursor Color
Applies a color to the chosen crosshair images, can be used for multiple players. Specify in HTML/CSS format (e.g. #aabbcc)

Horizontal Sensitivity
Vertical Sensitivity
Adjusts the correspondance between physical and virtual mouse movement.

Genre : Fighting / Action / Adventure / Survival horror / Adventure / First Person Shooter / Tactical RPG……etc.

### CODE REVIEW

**Comment by zkdpower** [comment]
0.1-5923 version has fatal defect, graphical problems in quite a few games.

**Comment by stenzek** [comment]
What games specifically? My automated testing showed no regressions.
Also list the settings you're using.

**Comment by stenzek** [comment]
> Genre : Fighting / Action / Adventure / Survival horror / Adventure / First Person Shooter / Tactical RPG……etc.

This is part of the game database, and not translatable.

**Comment by zkdpower** [comment]
> What games specifically? My automated testing showed no regressions. Also list the settings you're using.

I accidentally turned on cpu mode and forgot to turn it off.

**Comment by zkdpower** [comment]
dear stenzek:


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Please help me adding string for my simple-chinese translation.


Automatic
自动


Stretch To Fill
拉伸以填充


Nearest-Neighbor
最近邻
Bilinear (Smooth)
双线性 (光滑)
Nearest-Neighbor (Integer)
最近邻 (整数)
Bilinear (Sharp)
双线性 (锐化)


Disabled
禁用
Overlay Wireframe
覆盖线框
Only Wireframe
只是线框


Cursor Color
光标颜色
Applies a color to the chosen crosshair images, can be used for multiple players. Specify in HTML/CSS format (e.g. #aabbcc)
将颜色应用于所选的十字准星图像，可用于多个玩家。以HTML/CSS格式指定 (例如 #aabbcc)


Horizontal Sensitivity
水平灵敏度


Vertical Sensitivity
垂直灵敏度


Adjusts the correspondance between physical and virtual mouse movement.
调整物理和虚拟鼠标移动之间的对应关系。
&nbsp;


游戏音乐种花
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: "Connor ***@***.***&gt;; 
发送时间: 2023年10月10日(星期二) 晚上11:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stenzek/duckstation] update Simple-Chinese Translation. (PR #3028)





 
Merged #3028 into master.

**Comment by stenzek** [comment]
Those strings seem fine in the pt-br translation, so it's not an issue with the application.

Make sure you've run lupdate on an up-to-date tree.

**Comment by zkdpower** [comment]
&nbsp;Dear Stenzek:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;when i play tekken 3, crash and jump this.




游戏音乐种花
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: "Connor ***@***.***&gt;; 
发送时间: 2023年10月12日(星期四) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stenzek/duckstation] update Simple-Chinese Translation. (PR #3028)





 
Those strings seem fine in the pt-br translation, so it's not an issue with the application.
 
Make sure you've run lupdate on an up-to-date tree.

**Pull request merged**
