### PR TITLE
Update gamesettings.ini

### PR DESCRIPTION
**Pull request by 6lackmag3**
force digital for Mortal Kombat 4

### CODE REVIEW

**Comment by ggrtk** [comment]
As a postmortem for this, turns out the game doesn't do anything special, it just has shoddy pad handling. The `DUAL SHOCK ENABLED/DISABLED` options in the menu is poorly named and just tells the software to attempt a rumble configuration rewrite and begin sending appropriate rumble bytes to any controllers that it had previously detected to be a DualShock controller (regardless of whether or not the rumble configuration succeeded, and even when the user has already replugged a different controller type).

**Comment by 6lackmag3** [comment]
@ggrtk  ok but it wont read inputs in Analog Mode anyway. Digital is indeed needed to play this game.

**Comment by ggrtk** [comment]
Right, I was checking to rule out the possibility from the discussion yesterday with Stenzek that the game was relying on a DualShock toggling detection feature that we hadn't implemented. Hence my statement that the game's pad handling is just poorly programmed and isn't actually doing anything special.

**Comment by stenzek** [comment]
Sounds good, many thanks for confirming @ggrtk !

**Pull request merged**
