### PR TITLE
Update Simple-Chinese translation to latest.

### PR DESCRIPTION
**Pull request by zkdpower**

### CODE REVIEW

**Comment by zkdpower** [comment]
Dear Stenzek:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; how to update the latest language.ts file?
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;the former way is synchronize you repository, and find update_translations.bat under my&nbsp;Git hub directory "C:\Users\86181\Documents\GitHub\duckstation\src\duckstation-qt" , That doesn't working recent days, how to solve?



&nbsp;


游戏音乐种花
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Connor ***@***.***&gt;; 
发送时间: 2022年10月23日(星期天) 中午12:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stenzek/duckstation] Update Simple-Chinese translation to latest. (PR #2916)





 
Merged #2916 into master.

**Comment by stenzek** [comment]
The scripts in `src/duckstation-qt/translations` have been updated to the new dependency package, I just haven't had the time to document it yet. You can grab `deps-x64.7z` from https://github.com/stenzek/duckstation-ext-qt-minimal/releases/tag/latest, and extract it to the `dep/msvc` directory.

**Comment by zkdpower** [comment]
dear stenzek:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; even latest translation still missing many Formerly owned.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; besides, the error pop message in Big Picture mode should same as other.









&nbsp;


游戏音乐种花
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Connor ***@***.***&gt;; 
发送时间: 2023年9月27日(星期三) 晚上8:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stenzek/duckstation] Update Simple-Chinese translation to latest. (PR #2916)





 
The scripts in src/duckstation-qt/translations have been updated to the new dependency package, I just haven't had the time to document it yet. You can grab deps-x64.7z from https://github.com/stenzek/duckstation-ext-qt-minimal/releases/tag/latest, and extract it to the dep/msvc directory.

**Comment by zkdpower** [comment]
Dear stenzek:&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; please help me fix&nbsp;duckstation-qt_zh-CN.ts, keep the latest, remove the redundant(gray), i am unable to deal. my update method is always fork you latest repository and "update_translations.bat". now it seems hading problem, too many gray branch.




游戏音乐种花
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stenzek/duckstation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 晚上8:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stenzek/duckstation] Update Simple-Chinese translation to latest. (PR #2916)





 
The scripts in src/duckstation-qt/translations have been updated to the new dependency package, I just haven't had the time to document it yet. You can grab deps-x64.7z from https://github.com/stenzek/duckstation-ext-qt-minimal/releases/tag/latest, and extract it to the dep/msvc directory.

**Comment by andercard0** [comment]
> Dear stenzek:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; please help me fix&nbsp;duckstation-qt_zh-CN.ts, keep the latest, remove the redundant(gray), i am unable to deal. my update method is always fork you latest repository and "update_translations.bat". now it seems hading problem, too many gray branch. 游戏音乐种花 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "stenzek/duckstation" ***@***.***&gt;; 发送时间:&nbsp;2023年9月27日(星期三) 晚上8:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [stenzek/duckstation] Update Simple-Chinese translation to latest. (PR #2916) The scripts in src/duckstation-qt/translations have been updated to the new dependency package, I just haven't had the time to document it yet. You can grab deps-x64.7z from https://github.com/stenzek/duckstation-ext-qt-minimal/releases/tag/latest, and extract it to the dep/msvc directory. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hi,
Here it is the file updated with all the new strings. Note: I did not remove any of your obsolete lines. 
[duckstation-qt_zh-CN.zip](https://github.com/stenzek/duckstation/files/12840734/duckstation-qt_zh-CN.zip)

**Comment by stenzek** [comment]
`-no-obsolete` on `lupdate` will remove obsolete/vanished strings. See https://doc.qt.io/qt-6/linguist-lupdate.html

**Comment by stenzek** [comment]
I probably should just move things to Crowdin... too busy for that at the moment, though.

**Pull request merged**
