### PR TITLE
Adding crt-guest-advanced-HD shader

### PR DESCRIPTION
**Pull request by Michael-Prince-Sharpe**

### CODE REVIEW

**Comment by Michael-Prince-Sharpe** [comment]
Sorry about that, hopefully this restructure should fix that. The shader is public domain like crt-royale. (public licence v3)

**Comment by stenzek** [comment]
License header in the file shows GPLv2+, therefore a copyright/attribution statement is absolutely required.

**Comment by Michael-Prince-Sharpe** [comment]
Sorry about the typo, I mean v2 not 3 (or as you said v2+) my communication is terrible I went back and changed it, I've added relevant information under the files asked. Is this alright? Just let me know if it is.

**Comment by stenzek** [comment]
Line endings look like they've been changed accidentially.

**Comment by Michael-Prince-Sharpe** [comment]
Thanks, turns out it was a problem with my editors so used github itself to edit the thirdparty and source files so here's hoping this should fix the issue and github indicates that it doesn't conflct.

**Pull request merged**
