### PR TITLE
Bus: Increase the number of ticks for RAM reads

### PR DESCRIPTION
**Pull request by stenzek**
Fixes timings issues in:
- Rollcage Stage II PAL
- Tungsta Legend of Faith PAL
- Tom and Jerry in House Trap PAL
- Crash Bash PAL
- Destrega PAL
- The Note PAL
- Silent Hill cutscene (when icache is enabled)
- Legend of Legaia

No known regressions... yet.

### CODE REVIEW

**Comment by DarkSwan86** [comment]
Tested the latest artifact for Windows and indeed fixes #1046 , i've also played a bit Medievil, Tekken 3 and Gdarius (all PAL) and there are no drawbacks to this change. Nice works @stenzek !

**Comment by stenzek** [comment]
@DarkSwan86 many thanks for testing. I still have to confirm the average bandwidth with my console, so I'm not merging it until then, but it's good to know there's no regressions so far.

**Comment by GoodWall533** [comment]
I decided to test SH on that cutscene again with the interpreter and forcing  icache through the game properties to see if works normally and unfortunatly the problem still persists.

**Comment by stenzek** [comment]
> I decided to test SH on that cutscene again with the interpreter and forcing icache through the game properties to see if works normally and unfortunatly the problem still persists.

Did you test with this PR build or on master/latest? Just checked again and it is definitely fixed here with these changes.

**Comment by GoodWall533** [comment]
> > I decided to test SH on that cutscene again with the interpreter and forcing icache through the game properties to see if works normally and unfortunatly the problem still persists.
> 
> Did you test with this PR build or on master/latest? It's not merged yet.
> 
> I Just checked again and it is definitely fixed here with these changes.

Oh. It's just me being a dumbass. I was using the lastest build. I didn't bother to check this particular PR build. But it works fine this time around with forced icache. Don't know about the other games though.

**Pull request merged**
