### PR TITLE
Update Simple-Chinese language file to latest

### PR DESCRIPTION
**Pull request by zkdpower**
Update Simple-Chinese language file to latest

### CODE REVIEW

**Comment by zkdpower** [comment]
please add strings for new osd message.

**Comment by stenzek** [comment]
> please add strings for new osd message.

Which messages are missing?

**Comment by zkdpower** [comment]
Memory card at " …………" could not be read, formatting.

**Comment by stenzek** [comment]
> Memory card at " …………" could not be read, formatting.

Fixed in https://github.com/stenzek/duckstation/commit/24c373245ebdab946f11627520edea76e1f23b8e

**Comment by zkdpower** [comment]
do you need some new icon for duckstation? i see "shortcut key setting" and "game list setting" using different icon between inner with outer, perhaps unified is more better.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Connor McLaughlin"<notifications@github.com&gt;; 
发送时间: 2021年1月7日(星期四) 上午10:20
收件人: "stenzek/duckstation"<duckstation@noreply.github.com&gt;; 
抄送: "游戏音乐种花"<31569706@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [stenzek/duckstation] Update Simple-Chinese language file to latest (#1402)





  
Memory card at " …………" could not be read, formatting.
  
Fixed in 24c3732
 
&mdash;

**Comment by zkdpower** [comment]
Dear Stenzek:&nbsp; &nbsp; &nbsp; &nbsp; Did you forget to update the Translation string/code for Chinese/Japanese/ETC……? why recently new version don't have any source text update.





&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; zkdpower

**Comment by stenzek** [comment]
Which strings aren't showing up? I did an `lupdate` and the latest stuff (e.g. image patches) gets listed fine.

**Comment by zkdpower** [comment]
since your add "seek speedup" function, after that, all new translatable strings no longer appear.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stenzek/duckstation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stenzek/duckstation] Update Simple-Chinese language file to latest (#1402)





 
Which strings aren't showing up? I did an lupdate and the latest stuff (e.g. image patches) gets listed fine.

**Comment by stenzek** [comment]
It seems to update fine here. Here's the file `lupdate` generated for me:

[duckstation-qt_zh-cn.zip](https://github.com/stenzek/duckstation/files/6595626/duckstation-qt_zh-cn.zip)

**Pull request merged**
