### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by shikulja**

### CODE REVIEW

**Comment by stenzek** [comment]
Not sure why you need to ignore .qm? The only qm files should be in directories which are already ignored.

**Comment by shikulja** [comment]
Before committing, I create a qm file for testing. He often asks to be added to commits too
image

**Comment by stenzek** [comment]
Sounds like a local issue then. Please drop that commit.

**Comment by shikulja** [comment]
GitHub Desktop + win11 nothing special

**Pull request closed without merging**
